Replace BindableEvents with Signal
RyanLua/Satchel pull request #48
Opened 2024-01-20 20:52 UTC by Katrist

## Description

Improved signalling

## Changes Made

Replaced BindableEvents with a Signal module

## Checklist

- [X] I have tested these changes thoroughly.
- [X] I have reviewed my code for any potential errors or issues.
- [X] I have followed the code style guidelines for this project.

## Additional Notes

Signal is far more performant than BindableEvents, which is why this replacement is happening.
Also, apologies if I haven't added the module correctly.

Source: https://devforum.roblox.com/t/lua-signal-class-comparison-optimal-goodsignal-class/1387063

## Code of Conduct

By submitting this issue, I agree to follow the [Code of Conduct](CODE_OF_CONDUCT.md).

2024-01-20 23:34 UTC, RyanLua requested changes
Some changes I would suggest on top of my comments are:

* Types for Signal
* Removing instances where the Signal is `:Destroy`ed and `:Disconnect`ed where we no longer need it
* Updating methods to return the correct types

And if you can, update documentation as needed. I probably could do that myself though.

2024-01-20 23:34 UTC, RyanLua commented on src/init.lua
> +BackpackScript.BackpackItemRemoved = Signal.new() -- Fires when an item is removed from the backpack
Adding types for `Signal` and asserting them here would be useful.

2024-01-20 23:34 UTC, RyanLua commented on src/init.lua
> +local Signal = require(script.Packages.Signal)
Not a package.

```suggestion
local Signal = require(script.Signal)
```

2024-01-20 23:34 UTC, RyanLua commented on src/init.lua
> +	BackpackScript.StateChanged:Connect(function(isNowOpen: boolean)
`BackpackScript.StateChanged` returns the type `BindableEvent` on line 2148 so we would need to correct. This could cause a warning here.

2024-01-21 17:44 UTC, Katrist commented
Just realized that this wouldn't be possible since I'm assuming you want users to be able to access events like StateChanged. Apologies.

2024-01-21 17:44 UTC, closed without merging